server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Angular: rutas SPA — si no encuentra el archivo, devuelve index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy al backend Spring Boot para las llamadas a la API
    location /api/ {
        proxy_pass http://api:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy al backend para las imágenes subidas
    location /uploads/ {
        proxy_pass http://api:8080/uploads/;
    }
}
